# Generated by Django 5.1.2 on 2024-11-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
