# Generated by Django 5.1.2 on 2024-11-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_author_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='book.genre', verbose_name='gênero'),
        ),
    ]
